[tool.poetry]
name = "csa-lab3"
version = "0.1.0"
description = ""
authors = ["tolst <tolstykh_mariia@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
